sudo: required
services:
  - docker

before_install:
  - docker build -t ajdin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ajdin/react-test npm test -- --coverage

after_success:
  - docker build -t ajdin/multi-client ./client
  - docker build -t ajdin/multi-nginx ./nginx
  - docker build -t ajdin/multi-server ./server
  - docker build -t ajdin/multi-worker ./worker
  # Log into docker CLI, u travisu dodamo varijable
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take these images and push them to docker hub